spring:
  datasource:
    url: jdbc:mysql://localhost:3306/amovie?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      file-size-threshold: 10MB
  mail:
    username: 1627844806@qq.com
    password: dxogcixlccrufcgg
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true

thymeleaf:
  prefix: classpath:/templates/
  suffix: .html
  cache: false

mybatis:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jxau.wmy.pojo


pagehelper:
  reasonable: true

filepath: G:\my_document\upload
